### ISSUE TITLE
Error using multi_logistic loss layer

### ISSUE THREAD

**Issue by rogihee** [dmlc/cxxnet#139] opened 2015-05-11 13:46 UTC
I'm trying to use the multi_logistic loss layer. However.. no metric seems to work with it.
Looking at the source code Logloss metric assumes 1 output OR softmax.
So I tried rsme which seemed likely to work but it gives an error.

See my definition below:

layer[16->16] = multi_logistic:test123
  target = test123
netconfig=end

label_vec[0,10) = test123
label_width = 10

# evaluation metric
metric = rmse

ERROR
"in rmse metric the size of prediction and label must be te same"

Which metric / config am I supposed to use with multi_logistic ?
Thanks in advance...

**Comment by winstywang** [comment] 2015-05-12 10:45
Hi, good catch, I will fix it in a couple of days.

**Comment by zhangchen-qinyinghua** [comment] 2015-05-22 04:10
Hi,
I met the same problem when doing multi_label training.
And the solution is:

Always name your first label_vec as "label", like the following:

layer[16->16] = multi_logistic:test123
target = label
netconfig=end

label_vec[0,10) = label
label_width = 10


This bug seems to be caused by the initialization of the NetConfig.
Check the source code here(https://github.com/dmlc/cxxnet/blob/master/src/nnet/nnet_config.h)

Around line 114, reads.
 NetConfig(void) {
    updater_type = "sgd";
    sync_type = "simple";
    label_name_map["label"] = 0;
    label_range.push_back(std::make_pair(0, 1));
  }

So by default, cxxnet just insert a label named "label" whit range [0,1)
And this resulted in the bug we met.

BTW,
why cxxnet pays so much effort to parse the config file all by itself.
Isn't it a good idea to use some third-part libs like protobuf and googleflags, as Caffe did.

**Comment by winstywang** [comment] 2015-05-25 12:31
Fixed in this commit: https://github.com/dmlc/cxxnet/commit/6c7ffe34cb73d5f2bbdf7e3256cea9d3496666da You can also use logloss and error in multilabel traning. I have no multilabel dataset currently. So please feel free to try it. If you have further questions, please let me know.

**Closed by winstywang** 2015-05-25 12:31 UTC

**Comment by rogihee** [comment] 2015-05-26 09:50
Thanks for the fix!
