### ISSUE TITLE
ImageNet example

### ISSUE THREAD

**Issue by ommiissyu** [dmlc/cxxnet#84] opened 2015-04-02 03:22 UTC
Hi，

I am training the ImageNet just using the example configure.
But after training 20 round, I found the error rate did not decrease. The output is like this:
```bash
round        0:[    5000] 6907 sec elapsed[1]^[ train-error:0.998988    train-rec@1:0.001031    train-rec@5:0.00505042  test-error:0.999        test-rec@1:0.00102      test-rec@5:0.0048
round        1:[    5000] 13890 sec elapsed[2]  train-error:0.998985    train-rec@1:0.00101383  train-rec@5:0.00493959  test-error:0.999        test-rec@1:0.00126      test-rec@5:0.00494
```

**Comment by antinucleon** [comment] 2015-04-02 19:22
Thanks. I will check it this weekend because I deleted imagenet data a few days ago.

**Comment by ommiissyu** [comment] 2015-04-03 03:23
Thank you. I have try multi-gpu, single gpu. The result is the same.

**Comment by mli** [comment] 2015-04-03 17:09
bug confirmed: 3 x gtx 980, commit b3279c7

round        0:[    5000] 1955 sec elapsed[1]   train-error:0.999064    train-rec@1:0.000935783 train-rec@5:0.0048834   test-error:0.999        test-rec@1:0.001        tes\
t-rec@5:0.00504
round        1:[    5000] 3945 sec elapsed[2]   train-error:0.999042    train-rec@1:0.000957636 train-rec@5:0.0047515   test-error:0.999        test-rec@1:0.001        tes\
t-rec@5:0.005

the same config and data works fine on commit f955641, branch V2-refactor

**Comment by antinucleon** [comment] 2015-04-04 22:01
@mli I have pushed a fix, could you help me test again?

**Comment by mli** [comment] 2015-04-05 04:33
tested, seems there is still a bug

**Comment by antinucleon** [comment] 2015-04-05 05:30
OK. I will run on my machine tomorrow.

**Comment by mli** [comment] 2015-04-05 19:19
Did more experiments, sometimes it works, sometime not. The success chance for using uniform initialization is larger than the gaussian one. So I guess it goes to the odd bug we found some days ago.

**Comment by antinucleon** [comment] 2015-04-05 19:40
@mli xavier is based on uniform init. Old xavier was 2 times larger than current one. Maybe you can change this line https://github.com/dmlc/cxxnet/blob/master/src/layer/param.h#L122 to ```real_t a = sqrt(6.0f / (in_num + out_num));```  or choose a in the way https://github.com/dmlc/cxxnet/blob/master/src/layer/param.h#L128

**Comment by ommiissyu** [comment] 2015-04-07 03:13
I set the CUDNN = 0, and it work well now.

**Comment by rongrongxiangxin** [comment] 2015-04-07 07:40
still not work for me.

**Comment by superzrx** [comment] 2015-04-15 07:03
@rongrongxiangxin 
did you shuffle train image list? after shuffle it works for me

**Comment by rongrongxiangxin** [comment] 2015-04-15 08:36
@superzrx 
I did not shuffle the train list. I will try ,thanks a lot!

**Comment by superzrx** [comment] 2015-04-15 10:26
@rongrongxiangxin 
I retried with ImageNet.conf and cudnn on shuffled data but failed.  kaiming.conf is OK for me.

**Comment by rongrongxiangxin** [comment] 2015-04-16 05:00
@superzrx 
ImageNet.conf did not work too. Change 224 in kaiming.conf to 227, and it works OK.

**Comment by ommiissyu** [comment] 2015-04-17 03:45
@rongrongxiangxin, @superzrx ,kaiming.conf is OK, when you use cuDNN?

**Comment by superzrx** [comment] 2015-04-17 06:52
@ommiissyu  yes

**Comment by winstywang** [comment] 2015-04-17 07:04
Thanks all for testing. We are looking forward to see your contributions (new configs, features, all are welcome!) to the cxxnet.

**Comment by rongrongxiangxin** [comment] 2015-04-17 07:31
@ommiissyu 
kaiming.conf is ok with cudnn. I have not got the final accuray.

**Closed** 2015-06-18 08:58 UTC
