### ISSUE TITLE
MShadow TensorHolder Template Compilation

### ISSUE THREAD

**Issue by erogol** [dmlc/cxxnet#60] opened 2015-03-21 13:01 UTC
./mshadow/mshadow/./tensor_holder.h: In member function ‘mshadow::Shape<ndim> mshadow::ShapeHolder::get() const’:
./mshadow/mshadow/./tensor_holder.h:67:38: error: invalid use of member (did you forget the ‘&’ ?)
./mshadow/mshadow/./tensor_holder.h:69:15: error: could not convert template argument ‘mshadow::ShapeHolder::ndim’ to ‘int’
./mshadow/mshadow/./tensor_holder.h:69:18: error: invalid type in declaration before ‘;’ token
./mshadow/mshadow/./tensor_holder.h:70:29: error: invalid use of member (did you forget the ‘&’ ?)
./mshadow/mshadow/./tensor_holder.h:71:10: error: invalid types ‘int[mshadow::index_t {aka unsigned int}]’ for array subscript
./mshadow/mshadow/./tensor_holder.h: In member function ‘mshadow::ShapeHolder& mshadow::ShapeHolder::operator=(const mshadow::Shape<ndim>&)’:
./mshadow/mshadow/./tensor_holder.h:82:23: error: no matching function for call to ‘std::vector<unsigned int>::resize(<unresolved overloaded function type>)’
./mshadow/mshadow/./tensor_holder.h:82:23: note: candidate is:
/usr/include/c++/4.6/bits/stl_vector.h:629:7: note: void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type, std::vector<_Tp, _Alloc>::value_type) [with _Tp = unsigned int, _Alloc = std::allocator<unsigned int>, std::vector<_Tp, _Alloc>::size_type = long unsigned int, std::vector<_Tp, _Alloc>::value_type = unsigned int]
/usr/include/c++/4.6/bits/stl_vector.h:629:7: note:   no known conversion for argument 1 from ‘<unresolved overloaded function type>’ to ‘long unsigned int’
./mshadow/mshadow/./tensor_holder.h:83:29: error: invalid use of member (did you forget the ‘&’ ?)
./mshadow/mshadow/./tensor_holder.h: In member function ‘bool mshadow::ShapeHolder::operator==(const mshadow::Shape<ndim>&) const’:
./mshadow/mshadow/./tensor_holder.h:106:26: error: invalid use of member (did you forget the ‘&’ ?)
./mshadow/mshadow/./tensor_holder.h:107:29: error: invalid use of member (did you forget the ‘&’ ?)
make: *** [layer_cpu.o] Error 1

**Comment by winstywang** [comment] 2015-03-21 13:08
Please upgrade your gcc to 4.8 and try it again

**Comment by tqchen** [comment] 2015-03-21 16:38
This was due to TensorHolder using too deep nested template. I have removed the dep on tensor_holder.h in tensor.h. You should be now safe with g++4.6 if you pull the most recent mshadow

**Comment by tqchen** [comment] 2015-04-03 23:26
I am closing the issue and assume the issue is fixed as stated in last post

**Closed by tqchen** 2015-04-03 23:26 UTC
Labels: question

**Comment by erogol** [comment] 2015-04-06 16:03
yeah thanks, sorry for the unresponsiveness
