### ISSUE TITLE
cxxnet with the google net pretrained model

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/cxxnet#172] opened 2015-06-01 03:00 UTC
I download the pretrained google model, 0039.model and create a conf, test-goog.conf file (see below) to do a prediction, by using 
../../cxxnet ./test-goog.conf
There is an error message below with the above command:

finish initialization with 1 devices
ConvolutionLayer: LoadModel invalid model file

Is anything wrong with the test-goog.conf below:

pred = pred.txt
iter = image
  image_list = "pred.lst"
  image_root = "/home/hevc/src/cxxnet/images"
  image_mean = "mean_224.bin"
#no random crop and mirror in test
iter = end
task = pred
model_in = ./models/0039.model

netconfig = start
The rest is copied from Inception-BN.conf
Thanks

Kaishi

**Comment by antinucleon** [comment] 2015-06-01 03:25
I just test on my machine with newest clone, there nothing wrong on my machine. 

model md5: ```9c96f20f9dfdc3a20ca73983e2851d34  0039.model```

**Comment by kaishijeng** [comment] 2015-06-01 03:39
Antinucleon:

I check the downloaded model with md5sum and it also gives me the md5 value as you have.
9c96f20f9dfdc3a20ca73983e2851d34.

How do you verify the model with cxxnet?
I will try to use the  latest clone code and see whether the error will go away or not.


FC

**Comment by antinucleon** [comment] 2015-06-01 03:41
I set conf to
```
eval = val
iter = imgbin
  image_list = /home/bing/Data/ImageNet/cxxnet/val/val.lst
  image_bin = /home/bing/Data/ImageNet/cxxnet/val/val.bin
  image_mean = "mean_224.bin"
iter = end
```
and I set ```model_in``` to check evaluation score.

**Comment by kaishijeng** [comment] 2015-06-01 04:09
No luck with the latest git pull. Still give me the same error.

Kaishi

**Comment by kaishijeng** [comment] 2015-06-01 04:18
Is this model only for GPU?
My system uses CPU.

Kaishi

**Comment by antinucleon** [comment] 2015-06-01 04:23
There is no difference of GPU/CPU model in cxxnet. I just try to set ```dev=cpu```, it also works well.

**Comment by zhongwen** [comment] 2015-06-02 15:49
Caused by inconsistent length of `long` type in 32-bit system. 

Fixed in 9df6af8. 

@kaishijeng Thx for reporting this.

**Closed by zhongwen** 2015-06-02 15:49 UTC
